from __future__ import annotations

import torch


def z_order_encode(x: torch.Tensor, y: torch.Tensor, z: torch.Tensor) -> torch.Tensor: ...

def z_order_decode(code: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]: ...

def hilbert_encode(x: torch.Tensor, y: torch.Tensor, z: torch.Tensor) -> torch.Tensor: ...

def hilbert_decode(code: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]: ...
